name: 📊 Update Progress

on:
  push:
    branches:
      - main
  schedule:
    - cron: "30 17 * * *"   # Runs daily at 11:00 PM IST (17:30 UTC)
  workflow_dispatch:         # Allow manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run update script
        run: python tools/update_readme.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "🔄 Auto-update progress [skip ci]"
          git push
