name: Update Progress

on:
  workflow_dispatch:
  push:
    paths:
      - "arrays/**"
      - "strings/**"
      - "dp/**"
      - "graphs/**"
      - "linked_list/**"

permissions:
  contents: write   # ✅ allow GitHub Actions to push changes

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Run update script
        run: python tools/update_readme.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md tools/progress.json
          git commit -m "Update Progress [skip ci]" || echo "No changes to commit"
          git push
