name: Rename DSA Files

on:
  push:
    branches:
      - main

jobs:
  rename:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run renamer
        run: |
          python3 tools/rename_and_track.py

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto-rename files" || echo "No changes to commit"
          git push
