name: Rename DSA Files

on:
  push:
    branches:
      - main

permissions:
  contents: write   # 👈 allows the bot to push changes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run renamer script
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          python tools/rename_and_track.py
          
          git add .
          git commit -m "Auto-rename files"
          git push
